name: relic_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # routing and state management
  go_router: ^13.2.0
  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4

  # api
  dio: ^5.4.1
  pretty_dio_logger: ^1.3.1

  # ui
  skeletonizer: ^1.1.0
  flutter_animate: ^4.5.0

  # utilities
  back_button_interceptor: ^7.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
